#!/usr/bin/env bash
set -euo pipefail

DONE_MARKER="colab_worker_logs/v5_logging_s3magloss_batch_done.json"
if [ -f "$DONE_MARKER" ]; then
  echo "v5 logging/S3-magnitude-loss batch already completed; marker exists at $DONE_MARKER"
  exit 0
fi

mkdir -p colab_worker_logs

V5_CSV=$(ls -td training_results/feature_regression_enhanced/enhanced_v5_s3_tail60k_*/training_features_enhanced.csv 2>/dev/null | head -1 || true)
if [ -z "$V5_CSV" ]; then
  echo "Missing v5 S3-tail cached CSV; running v5 setup workflow first."
  bash scripts/run_colab_v5_s3_tail60k_workflow.sh
  V5_CSV=$(ls -td training_results/feature_regression_enhanced/enhanced_v5_s3_tail60k_*/training_features_enhanced.csv | head -1)
fi

BASE_CONFIG="configs/model_selection_batch_v5_logging_s3magloss.json"
RUNTIME_CONFIG="colab_worker_logs/model_selection_batch_v5_logging_s3magloss_runtime.json"
python3 - "$BASE_CONFIG" "$RUNTIME_CONFIG" "$V5_CSV" <<'PY'
import json
import sys
from pathlib import Path

base_config = Path(sys.argv[1])
runtime_config = Path(sys.argv[2])
csv_path = sys.argv[3]

config = json.loads(base_config.read_text())
config.setdefault("defaults", {})["csv_path"] = csv_path
config["runtime_csv_path"] = csv_path
config["runtime_note"] = "Generated by run_colab_v5_logging_s3magloss_workflow.sh to pin the v5 CSV path."
runtime_config.write_text(json.dumps(config, indent=2) + "\n")
print("runtime batch config:", runtime_config)
print("v5 csv:", csv_path)
PY

python3 scripts/run_model_selection_batch.py \
  --batch-config "$RUNTIME_CONFIG" \
  --output-root training_results/model_selection_loop \
  --summary-root training_results/model_selection_batches \
  --max-runtime-minutes 170

LOGGING_REF_RUN=$(ls -td training_results/model_selection_loop/D66_grouped_width320_lr6e-4_dropout0.075_s3tail60k_logging_ref_seed23_* 2>/dev/null | head -1 || true)
S3MAG005_RUN=$(ls -td training_results/model_selection_loop/D66_grouped_width320_lr6e-4_dropout0.075_s3tail60k_s3magloss_w0p05_seed23_* 2>/dev/null | head -1 || true)
S3MAG010_RUN=$(ls -td training_results/model_selection_loop/D66_grouped_width320_lr6e-4_dropout0.075_s3tail60k_s3magloss_w0p10_seed23_* 2>/dev/null | head -1 || true)

if [ -z "$LOGGING_REF_RUN" ] || [ -z "$S3MAG005_RUN" ] || [ -z "$S3MAG010_RUN" ]; then
  python3 - "$V5_CSV" "$LOGGING_REF_RUN" "$S3MAG005_RUN" "$S3MAG010_RUN" <<'PY'
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

Path("colab_worker_logs/v5_logging_s3magloss_batch_pending.json").write_text(
    json.dumps(
        {
            "status": "pending",
            "created_utc": datetime.now(timezone.utc).isoformat(),
            "workflow": "scripts/run_colab_v5_logging_s3magloss_workflow.sh",
            "dataset_csv": sys.argv[1],
            "runs": {
                "v5_logging_ref_seed23": sys.argv[2],
                "v5_s3magloss_w0p05_seed23": sys.argv[3],
                "v5_s3magloss_w0p10_seed23": sys.argv[4],
            },
            "note": "At least one candidate is not complete yet. The next worker cycle will continue the batch.",
        },
        indent=2,
    )
    + "\n"
)
PY
  echo "Batch is not complete yet; skipping audits until all candidate runs exist."
  exit 0
fi

python3 scripts/audit_s3_magnitude_metric.py \
  --run v5_logging_ref_seed23="$LOGGING_REF_RUN" \
  --run v5_s3magloss_w0p05_seed23="$S3MAG005_RUN" \
  --run v5_s3magloss_w0p10_seed23="$S3MAG010_RUN"

python3 scripts/audit_training_validation_loss_gap.py \
  --include-default-runs \
  --run "$LOGGING_REF_RUN" \
  --run "$S3MAG005_RUN" \
  --run "$S3MAG010_RUN"

python3 - "$DONE_MARKER" "$V5_CSV" "$LOGGING_REF_RUN" "$S3MAG005_RUN" "$S3MAG010_RUN" <<'PY'
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

marker = Path(sys.argv[1])
marker.write_text(
    json.dumps(
        {
            "status": "complete",
            "created_utc": datetime.now(timezone.utc).isoformat(),
            "workflow": "scripts/run_colab_v5_logging_s3magloss_workflow.sh",
            "dataset_csv": sys.argv[2],
            "runs": {
                "v5_logging_ref_seed23": sys.argv[3],
                "v5_s3magloss_w0p05_seed23": sys.argv[4],
                "v5_s3magloss_w0p10_seed23": sys.argv[5],
            },
            "diagnostics": [
                "repaired_training_history_logging",
                "s3_magnitude_metric_audit",
                "training_validation_loss_gap_audit",
            ],
        },
        indent=2,
    )
    + "\n"
)
print("done marker:", marker)
PY
