#!/usr/bin/env bash
set -euo pipefail

DONE_MARKER="colab_worker_logs/v13_1m_seed_repeat_residual_nn_done.json"
DRIVE_BACKUP_RUN_NAME_FILE="colab_worker_logs/v13_seed_repeat_residual_nn_drive_backup_run_name.txt"

if [ -f "$DONE_MARKER" ]; then
  echo "v13 1M seed-repeat residual-NN workflow already completed; marker exists at $DONE_MARKER"
  exit 0
fi

mkdir -p colab_worker_logs

if [ -f "$DRIVE_BACKUP_RUN_NAME_FILE" ]; then
  DRIVE_BACKUP_RUN_NAME=$(cat "$DRIVE_BACKUP_RUN_NAME_FILE")
else
  DRIVE_BACKUP_RUN_NAME="v13_seed_repeat_residual_nn_$(date -u +%Y%m%d_%H%M%S_utc)"
  printf '%s\n' "$DRIVE_BACKUP_RUN_NAME" > "$DRIVE_BACKUP_RUN_NAME_FILE"
fi

V13_CSV=$(ls -td training_results/feature_regression_enhanced/enhanced_v13_1m_spacefill_*/training_features_enhanced.csv 2>/dev/null | head -1 || true)
if [ -z "$V13_CSV" ]; then
  echo "Missing cached v13 1M CSV. Restore it from Google Drive before running seed-repeat diagnostics."
  exit 1
fi

V2_SPLIT_MANIFEST="configs/benchmark_split_v12_v2_row_keys.json"
if [ ! -f "$V2_SPLIT_MANIFEST" ]; then
  V12_CSV=$(ls -td training_results/feature_regression_enhanced/enhanced_v12_benchmark_v2_*/training_features_enhanced.csv 2>/dev/null | head -1 || true)
  V1_SPLIT_MANIFEST="configs/benchmark_split_v6_frozen_row_keys.json"
  if [ -z "$V12_CSV" ] || [ ! -f "$V1_SPLIT_MANIFEST" ]; then
    echo "Missing v12 CSV or v6 split manifest required to recreate benchmark-v2 split manifest."
    exit 1
  fi
  python3 scripts/write_benchmark_v2_split_manifest.py \
    --csv-path "$V12_CSV" \
    --base-manifest "$V1_SPLIT_MANIFEST" \
    --output "$V2_SPLIT_MANIFEST" \
    --new-dataset-version enhanced_v12_benchmark_v2 \
    --dataset-version enhanced_v12_benchmark_v2 \
    --overwrite
fi

BASE_CONFIG="configs/model_selection_batch_v13_1m_seed_repeats_residual_nn.json"
RUNTIME_CONFIG="colab_worker_logs/model_selection_batch_v13_1m_seed_repeats_residual_nn_runtime.json"
python3 - "$BASE_CONFIG" "$RUNTIME_CONFIG" "$V13_CSV" "$V2_SPLIT_MANIFEST" <<'PY'
import json
import sys
from pathlib import Path

base_config = Path(sys.argv[1])
runtime_config = Path(sys.argv[2])
csv_path = sys.argv[3]
manifest_path = sys.argv[4]

config = json.loads(base_config.read_text())
config.setdefault("defaults", {})["csv_path"] = csv_path
config.setdefault("defaults", {})["benchmark_split_manifest"] = manifest_path
config["runtime_csv_path"] = csv_path
config["runtime_benchmark_split_manifest"] = manifest_path
config["runtime_note"] = (
    "Generated by run_colab_v13_seed_repeat_residual_nn_workflow.sh. "
    "Runs v13 seed repeats on the cached 1M CSV and writes residual-vs-12D-NN diagnostics."
)
runtime_config.write_text(json.dumps(config, indent=2) + "\n")
print("runtime batch config:", runtime_config)
print("v13 csv:", csv_path)
print("benchmark-v2 split manifest:", manifest_path)
PY

python3 scripts/run_model_selection_batch.py \
  --batch-config "$RUNTIME_CONFIG" \
  --output-root training_results/model_selection_loop \
  --summary-root training_results/model_selection_batches \
  --max-runtime-minutes 360

echo "Updating Drive backup after v13 seed-repeat residual-NN diagnostics."
python3 scripts/backup_colab_state_to_drive.py --run-name "$DRIVE_BACKUP_RUN_NAME"

python3 - "$DONE_MARKER" "$V13_CSV" "$V2_SPLIT_MANIFEST" "$DRIVE_BACKUP_RUN_NAME" <<'PY'
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

marker = Path(sys.argv[1])
marker.write_text(
    json.dumps(
        {
            "status": "complete",
            "created_utc": datetime.now(timezone.utc).isoformat(),
            "workflow": "scripts/run_colab_v13_seed_repeat_residual_nn_workflow.sh",
            "dataset_csv": sys.argv[2],
            "benchmark_v2_split_manifest": sys.argv[3],
            "drive_backup_run_name": sys.argv[4],
            "diagnostics": [
                "v13_1m_seed_repeat_training",
                "residual_vs_12d_nearest_neighbor_distance",
                "vector_diagnostics",
                "per_target_diagnostics",
                "drive_backup"
            ],
            "decision": "Use seed variation plus residual-vs-NN distance to decide whether the next move is targeted data expansion or feature/model/loss improvement.",
        },
        indent=2,
    )
    + "\n"
)
print("done marker:", marker)
PY
