#!/usr/bin/env bash
set -euo pipefail

DONE_MARKER="colab_worker_logs/v8b_frozen_defocus_confirmation_done.json"
if [ -f "$DONE_MARKER" ]; then
  echo "v8b frozen defocus confirmation already completed; marker exists at $DONE_MARKER"
  exit 0
fi

mkdir -p colab_worker_logs

V6_CSV=$(ls -td training_results/feature_regression_enhanced/enhanced_v6_benchmark_gap100k_*/training_features_enhanced.csv 2>/dev/null | head -1 || true)
if [ -z "$V6_CSV" ]; then
  echo "Missing v6 benchmark-gap cached CSV; running v6 setup workflow first."
  bash scripts/run_colab_v6_benchmark_gap100k_workflow.sh
  V6_CSV=$(ls -td training_results/feature_regression_enhanced/enhanced_v6_benchmark_gap100k_*/training_features_enhanced.csv | head -1)
fi

FROZEN_SPLIT_MANIFEST="configs/benchmark_split_v6_frozen_row_keys.json"
python3 scripts/write_benchmark_split_manifest.py \
  --csv-path "$V6_CSV" \
  --output "$FROZEN_SPLIT_MANIFEST" \
  --dataset-version enhanced_v6_benchmark_gap100k

FULL_CSV=$(ls -td training_results/feature_regression_enhanced/enhanced_v8_c1diff_full_*/training_features_enhanced.csv 2>/dev/null | head -1 || true)
if [ -z "$FULL_CSV" ]; then
  python3 scripts/augment_defocus_difference_features.py \
    --source-csv "$V6_CSV" \
    --run-prefix enhanced_v8_c1diff_full \
    --dataset-version enhanced_v8_c1diff_full \
    --mode c1_defocus_full
  FULL_CSV=$(ls -td training_results/feature_regression_enhanced/enhanced_v8_c1diff_full_*/training_features_enhanced.csv | head -1)
fi

BASE_CONFIG="configs/model_selection_batch_v8b_frozen_defocus_confirmation.json"
RUNTIME_CONFIG="colab_worker_logs/model_selection_batch_v8b_frozen_defocus_confirmation_runtime.json"
python3 - "$BASE_CONFIG" "$RUNTIME_CONFIG" "$V6_CSV" "$FULL_CSV" "$FROZEN_SPLIT_MANIFEST" <<'PY'
import json
import sys
from pathlib import Path

base_config = Path(sys.argv[1])
runtime_config = Path(sys.argv[2])
csv_paths = {
    "v6": sys.argv[3],
    "c1diff_full": sys.argv[4],
}
manifest_path = Path(sys.argv[5])

config = json.loads(base_config.read_text())
for job in config.get("jobs", []):
    key = job.pop("csv_key", None)
    if key:
        job["csv_path"] = csv_paths[key]
config.setdefault("defaults", {})["benchmark_split_manifest"] = str(manifest_path)
config["runtime_csv_paths"] = csv_paths
config["runtime_benchmark_split_manifest"] = str(manifest_path)
config["runtime_note"] = (
    "Generated by run_colab_v8b_frozen_defocus_confirmation_workflow.sh "
    "to rerun the 66-feature baseline and full defocus-difference candidates "
    "with frozen benchmark split membership."
)
runtime_config.write_text(json.dumps(config, indent=2) + "\n")
print("runtime batch config:", runtime_config)
print("csv paths:", json.dumps(csv_paths, indent=2))
print("frozen benchmark split manifest:", manifest_path)
PY

python3 scripts/run_model_selection_batch.py \
  --batch-config "$RUNTIME_CONFIG" \
  --output-root training_results/model_selection_loop \
  --summary-root training_results/model_selection_batches \
  --max-runtime-minutes 210

RUNS=(
  "v8b_frozen_d66_seed23:D66_grouped_width320_lr6e-4_dropout0.075_v8b_frozen_d66_seed23"
  "v8b_frozen_c1diff_full_seed23:D66_grouped_width320_lr6e-4_dropout0.075_v8b_frozen_c1diff_full_seed23"
  "v8b_frozen_c1diff_full_seed7:D66_grouped_width320_lr6e-4_dropout0.075_v8b_frozen_c1diff_full_seed7"
)

COMPLETE_RUN_ARGS=()
COMPLETE_RUN_PATH_ARGS=()
MISSING_RUNS=()
for item in "${RUNS[@]}"; do
  label="${item%%:*}"
  candidate="${item#*:}"
  run_dir=$(ls -td training_results/model_selection_loop/"${candidate}"_* 2>/dev/null | head -1 || true)
  if [ -z "$run_dir" ]; then
    MISSING_RUNS+=("$label")
  else
    COMPLETE_RUN_ARGS+=(--run "$label=$run_dir")
    COMPLETE_RUN_PATH_ARGS+=(--run "$run_dir")
  fi
done

if [ "${#MISSING_RUNS[@]}" -gt 0 ]; then
  python3 - "$V6_CSV" "$FULL_CSV" "${MISSING_RUNS[@]}" <<'PY'
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

Path("colab_worker_logs/v8b_frozen_defocus_confirmation_pending.json").write_text(
    json.dumps(
        {
            "status": "pending",
            "created_utc": datetime.now(timezone.utc).isoformat(),
            "workflow": "scripts/run_colab_v8b_frozen_defocus_confirmation_workflow.sh",
            "csv_paths": {
                "v6": sys.argv[1],
                "c1diff_full": sys.argv[2],
            },
            "missing_runs": sys.argv[3:],
            "note": "At least one v8b candidate is not complete yet. The next worker cycle will continue the batch.",
        },
        indent=2,
    )
    + "\n"
)
PY
  echo "Batch is not complete yet; skipping audits until all v8b candidate runs exist."
  exit 0
fi

python3 scripts/audit_s3_magnitude_metric.py "${COMPLETE_RUN_ARGS[@]}"

python3 scripts/audit_training_validation_loss_gap.py \
  --include-default-runs \
  "${COMPLETE_RUN_PATH_ARGS[@]}"

python3 - "$DONE_MARKER" "$V6_CSV" "$FULL_CSV" "$FROZEN_SPLIT_MANIFEST" <<'PY'
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

marker = Path(sys.argv[1])
marker.write_text(
    json.dumps(
        {
            "status": "complete",
            "created_utc": datetime.now(timezone.utc).isoformat(),
            "workflow": "scripts/run_colab_v8b_frozen_defocus_confirmation_workflow.sh",
            "csv_paths": {
                "v6": sys.argv[2],
                "c1diff_full": sys.argv[3],
            },
            "frozen_benchmark_split_manifest": sys.argv[4],
            "diagnostics": [
                "frozen_benchmark_split_manifest",
                "defocus_difference_full_confirmation",
                "s3_magnitude_metric_audit",
                "training_validation_loss_gap_audit",
            ],
            "decision": "Compare full defocus-difference seed23/seed7 against the frozen 66-feature seed23 baseline before promotion.",
        },
        indent=2,
    )
    + "\n"
)
print("done marker:", marker)
PY
