#!/usr/bin/env bash
set -euo pipefail

DONE_MARKER="colab_worker_logs/v13_1m_d66_done.json"
SAMPLING_QUALITY_DIR="training_results/model_selection_reports/sampling_quality_v13_1m_d66"
DRIVE_BACKUP_RUN_NAME_FILE="colab_worker_logs/v13_1m_drive_backup_run_name.txt"

if [ -f "$DONE_MARKER" ]; then
  echo "v13 1M d66 workflow already completed; marker exists at $DONE_MARKER"
  exit 0
fi

mkdir -p colab_worker_logs

if [ -f "$DRIVE_BACKUP_RUN_NAME_FILE" ]; then
  DRIVE_BACKUP_RUN_NAME=$(cat "$DRIVE_BACKUP_RUN_NAME_FILE")
else
  DRIVE_BACKUP_RUN_NAME="v13_1m_$(date -u +%Y%m%d_%H%M%S_utc)"
  printf '%s\n' "$DRIVE_BACKUP_RUN_NAME" > "$DRIVE_BACKUP_RUN_NAME_FILE"
fi

V12_CSV=$(ls -td training_results/feature_regression_enhanced/enhanced_v12_benchmark_v2_*/training_features_enhanced.csv 2>/dev/null | head -1 || true)
if [ -z "$V12_CSV" ]; then
  echo "Missing cached v12 benchmark-v2 CSV. Restore it from Google Drive or rerun the v12 workflow before v13."
  exit 1
fi

V1_SPLIT_MANIFEST="configs/benchmark_split_v6_frozen_row_keys.json"
if [ ! -f "$V1_SPLIT_MANIFEST" ]; then
  V6_CSV=$(ls -td training_results/feature_regression_enhanced/enhanced_v6_benchmark_gap100k_*/training_features_enhanced.csv 2>/dev/null | head -1 || true)
  if [ -z "$V6_CSV" ]; then
    echo "Missing v6 cached CSV required to recreate benchmark-v1 split manifest."
    exit 1
  fi
  python3 scripts/write_benchmark_split_manifest.py \
    --csv-path "$V6_CSV" \
    --output "$V1_SPLIT_MANIFEST" \
    --dataset-version enhanced_v6_benchmark_gap100k \
    --overwrite
fi

V2_SPLIT_MANIFEST="configs/benchmark_split_v12_v2_row_keys.json"
python3 scripts/write_benchmark_v2_split_manifest.py \
  --csv-path "$V12_CSV" \
  --base-manifest "$V1_SPLIT_MANIFEST" \
  --output "$V2_SPLIT_MANIFEST" \
  --new-dataset-version enhanced_v12_benchmark_v2 \
  --dataset-version enhanced_v12_benchmark_v2 \
  --overwrite

V13_CSV=$(ls -td training_results/feature_regression_enhanced/enhanced_v13_1m_spacefill_*/training_features_enhanced.csv 2>/dev/null | head -1 || true)
if [ -z "$V13_CSV" ]; then
  python3 scripts/generate_targeted_enhanced_dataset.py \
    --parent-csv "$V12_CSV" \
    --run-prefix enhanced_v13_1m_spacefill \
    --dataset-version enhanced_v13_1m_spacefill \
    --case-counts-json configs/targeted_expansion_v13_1m.json \
    --seed 131 \
    --batch-base-cases 256 \
    --new-row-split-hint training_only
  V13_CSV=$(ls -td training_results/feature_regression_enhanced/enhanced_v13_1m_spacefill_*/training_features_enhanced.csv | head -1)
fi

echo "Backing up v13 generated dataset and current Colab state to Drive before training."
python3 scripts/backup_colab_state_to_drive.py --run-name "$DRIVE_BACKUP_RUN_NAME"

python3 scripts/report_sampling_quality.py \
  --csv-path "$V13_CSV" \
  --config configs/targeted_expansion_v13_1m.json \
  --benchmark-split-manifest "$V2_SPLIT_MANIFEST" \
  --output-dir "$SAMPLING_QUALITY_DIR"

BASE_CONFIG="configs/model_selection_batch_v13_1m_d66.json"
RUNTIME_CONFIG="colab_worker_logs/model_selection_batch_v13_1m_d66_runtime.json"
python3 - "$BASE_CONFIG" "$RUNTIME_CONFIG" "$V13_CSV" "$V2_SPLIT_MANIFEST" <<'PY'
import json
import sys
from pathlib import Path

base_config = Path(sys.argv[1])
runtime_config = Path(sys.argv[2])
csv_path = sys.argv[3]
manifest_path = sys.argv[4]

config = json.loads(base_config.read_text())
config.setdefault("defaults", {})["csv_path"] = csv_path
config.setdefault("defaults", {})["benchmark_split_manifest"] = manifest_path
config["runtime_csv_path"] = csv_path
config["runtime_benchmark_split_manifest"] = manifest_path
config["runtime_note"] = (
    "Generated by run_colab_v13_1m_d66_workflow.sh to pin the v13 "
    "1M train-eligible CSV and the frozen v12 benchmark-v2 split manifest. "
    "Rows marked benchmark_v2 remain held out."
)
runtime_config.write_text(json.dumps(config, indent=2) + "\n")
print("runtime batch config:", runtime_config)
print("v13 csv:", csv_path)
print("benchmark-v2 split manifest:", manifest_path)
PY

python3 scripts/run_model_selection_batch.py \
  --batch-config "$RUNTIME_CONFIG" \
  --output-root training_results/model_selection_loop \
  --summary-root training_results/model_selection_batches \
  --max-runtime-minutes 480

RUN_DIR=$(ls -td training_results/model_selection_loop/D66_grouped_width320_lr6e-4_dropout0.075_v13_1m_d66_seed7_* 2>/dev/null | head -1 || true)
if [ -z "$RUN_DIR" ]; then
  python3 - "$V13_CSV" "$SAMPLING_QUALITY_DIR" <<'PY'
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

Path("colab_worker_logs/v13_1m_d66_pending.json").write_text(
    json.dumps(
        {
            "status": "pending",
            "created_utc": datetime.now(timezone.utc).isoformat(),
            "workflow": "scripts/run_colab_v13_1m_d66_workflow.sh",
            "dataset_csv": sys.argv[1],
            "sampling_quality_dir": sys.argv[2],
            "note": "v13 CSV and sampling-quality report exist, but training did not finish in this cycle. The next worker cycle will continue.",
        },
        indent=2,
    )
    + "\n"
)
PY
  echo "v13 1M d66 training is not complete yet; leaving workflow pending."
  exit 0
fi

python3 scripts/audit_s3_magnitude_metric.py --run "v13_1m_d66_seed7=$RUN_DIR"
python3 scripts/audit_training_validation_loss_gap.py --include-default-runs --run "$RUN_DIR"

V13_BATCH_SUMMARY=$(ls -td training_results/model_selection_batches/v13_1m_d66_*/batch_summary.csv 2>/dev/null | head -1 || true)
if [ -n "$V13_BATCH_SUMMARY" ]; then
  python3 scripts/report_data_scale_learning_curve.py \
    --include-default-batches \
    --batch-summary "v13_1m=$V13_BATCH_SUMMARY"
fi

echo "Updating Drive backup after v13 training and audits."
python3 scripts/backup_colab_state_to_drive.py --run-name "$DRIVE_BACKUP_RUN_NAME"

python3 - "$DONE_MARKER" "$V13_CSV" "$V2_SPLIT_MANIFEST" "$RUN_DIR" "$SAMPLING_QUALITY_DIR" "$DRIVE_BACKUP_RUN_NAME" <<'PY'
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

marker = Path(sys.argv[1])
marker.write_text(
    json.dumps(
        {
            "status": "complete",
            "created_utc": datetime.now(timezone.utc).isoformat(),
            "workflow": "scripts/run_colab_v13_1m_d66_workflow.sh",
            "dataset_csv": sys.argv[2],
            "benchmark_v2_split_manifest": sys.argv[3],
            "run_dir": sys.argv[4],
            "sampling_quality_dir": sys.argv[5],
            "drive_backup_run_name": sys.argv[6],
            "diagnostics": [
                "sampling_quality_v13_1m_d66",
                "v13_1m_d66_training",
                "s3_magnitude_metric_audit",
                "training_validation_loss_gap_audit",
                "data_scale_learning_curve",
                "drive_backup"
            ],
            "decision": "Evaluate v13 1M coverage and benchmark metrics before deciding whether any expansion beyond 1M is necessary.",
        },
        indent=2,
    )
    + "\n"
)
print("done marker:", marker)
PY
