#!/usr/bin/env bash
set -euo pipefail

DONE_MARKER="colab_worker_logs/v9_gap250k_d66_batch_done.json"
if [ -f "$DONE_MARKER" ]; then
  echo "v9 250K d66 batch already completed; marker exists at $DONE_MARKER"
  exit 0
fi

mkdir -p colab_worker_logs

V6_CSV=$(ls -td training_results/feature_regression_enhanced/enhanced_v6_benchmark_gap100k_*/training_features_enhanced.csv 2>/dev/null | head -1 || true)
if [ -z "$V6_CSV" ]; then
  echo "Missing v6 benchmark-gap cached CSV; running v6 setup workflow first."
  bash scripts/run_colab_v6_benchmark_gap100k_workflow.sh
  V6_CSV=$(ls -td training_results/feature_regression_enhanced/enhanced_v6_benchmark_gap100k_*/training_features_enhanced.csv | head -1)
fi

FROZEN_SPLIT_MANIFEST="configs/benchmark_split_v6_frozen_row_keys.json"
python3 scripts/write_benchmark_split_manifest.py \
  --csv-path "$V6_CSV" \
  --output "$FROZEN_SPLIT_MANIFEST" \
  --dataset-version enhanced_v6_benchmark_gap100k \
  --overwrite

V9_CSV=$(ls -td training_results/feature_regression_enhanced/enhanced_v9_gap250k_*/training_features_enhanced.csv 2>/dev/null | head -1 || true)
if [ -z "$V9_CSV" ]; then
  python3 scripts/generate_targeted_enhanced_dataset.py \
    --parent-csv "$V6_CSV" \
    --run-prefix enhanced_v9_gap250k \
    --dataset-version enhanced_v9_gap250k \
    --case-counts-json configs/targeted_expansion_v9_250k.json \
    --seed 89 \
    --batch-base-cases 256
  V9_CSV=$(ls -td training_results/feature_regression_enhanced/enhanced_v9_gap250k_*/training_features_enhanced.csv | head -1)
fi

BASE_CONFIG="configs/model_selection_batch_v9_gap250k_d66.json"
RUNTIME_CONFIG="colab_worker_logs/model_selection_batch_v9_gap250k_d66_runtime.json"
python3 - "$BASE_CONFIG" "$RUNTIME_CONFIG" "$V9_CSV" "$FROZEN_SPLIT_MANIFEST" <<'PY'
import json
import sys
from pathlib import Path

base_config = Path(sys.argv[1])
runtime_config = Path(sys.argv[2])
csv_path = sys.argv[3]
manifest_path = sys.argv[4]

config = json.loads(base_config.read_text())
config.setdefault("defaults", {})["csv_path"] = csv_path
config.setdefault("defaults", {})["benchmark_split_manifest"] = manifest_path
config["runtime_csv_path"] = csv_path
config["runtime_benchmark_split_manifest"] = manifest_path
config["runtime_note"] = "Generated by run_colab_v9_gap250k_d66_workflow.sh to pin the v9 250K d66 CSV and frozen benchmark split manifest."
runtime_config.write_text(json.dumps(config, indent=2) + "\n")
print("runtime batch config:", runtime_config)
print("v9 csv:", csv_path)
print("frozen benchmark split manifest:", manifest_path)
PY

python3 scripts/run_model_selection_batch.py \
  --batch-config "$RUNTIME_CONFIG" \
  --output-root training_results/model_selection_loop \
  --summary-root training_results/model_selection_batches \
  --max-runtime-minutes 330

V9_SEED23_RUN=$(ls -td training_results/model_selection_loop/D66_grouped_width320_lr6e-4_dropout0.075_v9gap250k_d66_seed23_* 2>/dev/null | head -1 || true)
V9_SEED7_RUN=$(ls -td training_results/model_selection_loop/D66_grouped_width320_lr6e-4_dropout0.075_v9gap250k_d66_seed7_* 2>/dev/null | head -1 || true)

if [ -z "$V9_SEED23_RUN" ] || [ -z "$V9_SEED7_RUN" ]; then
  python3 - "$V9_CSV" "$V9_SEED23_RUN" "$V9_SEED7_RUN" <<'PY'
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

Path("colab_worker_logs/v9_gap250k_d66_batch_pending.json").write_text(
    json.dumps(
        {
            "status": "pending",
            "created_utc": datetime.now(timezone.utc).isoformat(),
            "workflow": "scripts/run_colab_v9_gap250k_d66_workflow.sh",
            "dataset_csv": sys.argv[1],
            "runs": {
                "v9_gap250k_d66_seed23": sys.argv[2],
                "v9_gap250k_d66_seed7": sys.argv[3],
            },
            "note": "At least one v9 250K d66 candidate is not complete yet. The next worker cycle will continue the batch.",
        },
        indent=2,
    )
    + "\n"
)
PY
  echo "v9 d66 batch is not complete yet; skipping audits until both candidate runs exist."
  exit 0
fi

python3 scripts/audit_s3_magnitude_metric.py \
  --run v9_gap250k_d66_seed23="$V9_SEED23_RUN" \
  --run v9_gap250k_d66_seed7="$V9_SEED7_RUN"

python3 scripts/audit_training_validation_loss_gap.py \
  --include-default-runs \
  --run "$V9_SEED23_RUN" \
  --run "$V9_SEED7_RUN"

python3 - "$DONE_MARKER" "$V9_CSV" "$V9_SEED23_RUN" "$V9_SEED7_RUN" "$FROZEN_SPLIT_MANIFEST" <<'PY'
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

marker = Path(sys.argv[1])
marker.write_text(
    json.dumps(
        {
            "status": "complete",
            "created_utc": datetime.now(timezone.utc).isoformat(),
            "workflow": "scripts/run_colab_v9_gap250k_d66_workflow.sh",
            "dataset_csv": sys.argv[2],
            "runs": {
                "v9_gap250k_d66_seed23": sys.argv[3],
                "v9_gap250k_d66_seed7": sys.argv[4],
            },
            "frozen_benchmark_split_manifest": sys.argv[5],
            "diagnostics": [
                "v9_250k_d66_training",
                "s3_magnitude_metric_audit",
                "training_validation_loss_gap_audit",
            ],
        },
        indent=2,
    )
    + "\n"
)
print("done marker:", marker)
PY
